#lang racket
(require images/icons/misc) ;Libreria para icono bomba
(require images/icons/control)
(require racket/date);Libreria para tomar la fecha
(provide (all-defined-out))


;________________________________________________________ESTRUCTURA PARA ALMACENAR LOS RESULTADOS________________________________________________________________________________________________________________________________________________
(define-struct Jugadores (nombre fecha hora tiempodejuego puntaje totaljugadas))
;_________________________________________________LISTAS PARA ALMACENAR LAS ESTRUCTURAS DE LOS RESULTADOS__________________________________________________________________________________________________________________________________
(define Recordjugadores (list))
;___________________________________________________VARIABLES FLAG PARA DETERMINAR LOS BOTONES CON MINA___________________________________________________________________________________________________________________________________
(define mina1 0)
(define mina2 0)
(define mina3 0)
(define mina4 0)
(define mina5 0)
(define mina6 0)
(define mina7 0)
(define mina8 0)
(define mina9 0)
(define mina10 0)
(define mina11 0)
(define mina12 0)
(define mina13 0)
(define mina14 0)
(define mina15 0)
(define mina16 0)
(define mina17 0)
(define mina18 0)
(define mina19 0)
(define mina20 0)
(define mina21 0)
(define mina22 0)
(define mina23 0)
(define mina24 0)
(define mina25 0)
(define mina26 0)
(define mina27 0)
(define mina28 0)
(define mina29 0)
(define mina30 0)
(define mina31 0)
(define mina32 0)
(define mina33 0)
(define mina34 0)
(define mina35 0)
(define mina36 0)
;________________________________________________________________VARIABLES PARA LOS ICONOS____________________________________________________________________________________________________________________________________________________________
(define minaI1 0)
(define minaI2 0)
(define minaI3 0)
(define minaI4 0)
(define minaI5 0)
(define minaI6 0)
(define minaI7 0)
(define minaI8 0)
(define minaI9 0)
(define minaI10 0)
(define minaI11 0)
(define minaI12 0)
(define minaI13 0)
(define minaI14 0)
(define minaI15 0)
(define minaI16 0)
(define minaI17 0)
(define minaI18 0)
(define minaI19 0)
(define minaI20 0)
(define minaI21 0)
(define minaI22 0)
(define minaI23 0)
(define minaI24 0)
(define minaI25 0)
(define minaI26 0)
(define minaI27 0)
(define minaI28 0)
(define minaI29 0)
(define minaI30 0)
(define minaI31 0)
(define minaI32 0)
(define minaI33 0)
(define minaI34 0)
(define minaI35 0)
(define minaI36 0)
;________________________________________________________________PROBABILIDAD 20% random 5____________________________________________________________________________________________________________________________________________________________
;________________________________________________________________PROBABILIDAD 50% random 2
;________________________________________________________________PROBABILIDAD 80% random 5
;________________________________________________________________PROBABILIDAD 90% random 10
(define (procesoasignarmina b)
  (set!  mina1 (random b))
  (set!  mina2 (random b))
  (set!  mina3 (random b))
  (set!  mina4 (random b))
  (set!  mina5 (random b))
  (set!  mina6 (random b))
  (set!  mina7 (random b))
  (set!  mina8 (random b))
  (set!  mina9 (random b))
  (set!  mina10 (random b))
  (set!  mina11 (random b))
  (set!  mina12 (random b))
  (set!  mina13 (random b))
  (set!  mina14 (random b))
  (set!  mina15 (random b))
  (set!  mina16 (random b))
  (set!  mina17 (random b))
  (set!  mina18 (random b))
  (set!  mina19 (random b))
  (set!  mina20 (random b))
  (set!  mina21 (random b))
  (set!  mina22 (random b))
  (set!  mina23 (random b))
  (set!  mina24 (random b))
  (set!  mina25 (random b))
  (set!  mina26 (random b))
  (set!  mina27 (random b))
  (set!  mina28 (random b))
  (set!  mina29 (random b))
  (set!  mina30 (random b))
  (set!  mina31 (random b))
  (set!  mina32 (random b))
  (set!  mina33 (random b))
  (set!  mina34 (random b))
  (set!  mina35 (random b))
  (set!  mina36 (random b))

  )


;_________________________________________________________ASIGNAR BOMBAS DE PROBABILIDAD 20% Y 50%_______________________________________________________________________________________________________________________________________________
(define (procesovariablemina b)
  (if (= mina1 1) (set! mina1 "BOOM") (set! mina1 ""))
  (if (= mina2 1) (set! mina2 "BOOM") (set! mina2 ""))
  (if (= mina3 1) (set! mina3 "BOOM") (set! mina3 ""))
  (if (= mina4 1) (set! mina4 "BOOM") (set! mina4 ""))  
  (if (= mina5 1) (set! mina5 "BOOM") (set! mina5 ""))
  (if (= mina6 1) (set! mina6 "BOOM") (set! mina6 ""))
  (if (= mina7 1) (set! mina7 "BOOM") (set! mina7 ""))  
  (if (= mina8 1) (set! mina8 "BOOM") (set! mina8 ""))
  (if (= mina9 1) (set! mina9 "BOOM") (set! mina9 ""))
  (if (= mina10 1) (set! mina10 "BOOM") (set! mina10 ""))
  (if (= mina11 1) (set! mina11 "BOOM") (set! mina11 ""))
  (if (= mina12 1) (set! mina12 "BOOM") (set! mina12 ""))
  (if (= mina13 1) (set! mina13 "BOOM") (set! mina13 ""))
  (if (= mina14 1) (set! mina14 "BOOM") (set! mina14 ""))
  (if (= mina15 1) (set! mina15 "BOOM") (set! mina15 ""))
  (if (= mina16 1) (set! mina16 "BOOM") (set! mina16 ""))
  (if (= mina17 1) (set! mina17 "BOOM") (set! mina17 ""))
  (if (= mina18 1) (set! mina18 "BOOM") (set! mina18 ""))
  (if (= mina19 1) (set! mina19 "BOOM") (set! mina19 ""))
  (if (= mina20 1) (set! mina20 "BOOM") (set! mina20 ""))
  (if (= mina21 1) (set! mina21 "BOOM") (set! mina21 ""))
  (if (= mina22 1) (set! mina22 "BOOM") (set! mina22 ""))
  (if (= mina23 1) (set! mina23 "BOOM") (set! mina23 ""))
  (if (= mina24 1) (set! mina24 "BOOM") (set! mina24 ""))
  (if (= mina25 1) (set! mina25 "BOOM") (set! mina25 ""))
  (if (= mina26 1) (set! mina26 "BOOM") (set! mina26 ""))
  (if (= mina27 1) (set! mina27 "BOOM") (set! mina27 ""))
  (if (= mina28 1) (set! mina28 "BOOM") (set! mina28 ""))
  (if (= mina29 1) (set! mina29 "BOOM") (set! mina29 ""))
  (if (= mina30 1) (set! mina30 "BOOM") (set! mina30 ""))
  (if (= mina31 1) (set! mina31 "BOOM") (set! mina31 ""))
  (if (= mina32 1) (set! mina32 "BOOM") (set! mina32 ""))
  (if (= mina33 1) (set! mina33 "BOOM") (set! mina33 ""))
  (if (= mina34 1) (set! mina34 "BOOM") (set! mina34 ""))
  (if (= mina35 1) (set! mina35 "BOOM") (set! mina35 ""))
  (if (= mina36 1) (set! mina36 "BOOM") (set! mina36 ""))

  (if  (string=? mina1 mina2 mina3 mina4 mina5 mina6 mina7 mina8 mina9 mina10 mina11 mina12 mina13 mina14 mina15 mina16 "BOOM")
    (begin (procesoasignarmina b)(procesovariablemina)) (display ""))
  
  (if  (string=? mina1 mina2 mina3 mina4 mina5 mina6 mina7 mina8 mina9 mina10 mina11 mina12 mina13 mina14 mina15 mina16
                  mina17 mina18 mina19 mina20 mina21 mina22 mina23 mina24 mina25 "BOOM")
    (begin (procesoasignarmina b)(procesovariablemina)) (display ""))
  
  (if  (string=? mina1 mina2 mina3 mina4 mina5 mina6 mina7 mina8 mina9 mina10 mina11 mina12 mina13 mina14 mina15 mina16
                  mina17 mina18 mina19 mina20 mina21 mina22 mina23 mina24 mina25 mina26 mina27 mina28 mina29 mina30 mina31
                   mina32 mina33 mina34 mina35 mina36 "BOOM")
    (begin (procesoasignarmina b)(procesovariablemina)) (display "")))
  
;________________________________________________________ASIGNAR BOMBA DE PROBABILIDAD 80% a=4 y 90% a=9  b= probabilidad en el random ______________________________________________________________________________________________________________
(define (procesovariablemina2 a b)
  (if (not(= mina1 a)) (set! mina1 "BOOM") (set! mina1 ""))
  (if (not(= mina2 a)) (set! mina2 "BOOM") (set! mina2 ""))
  (if (not(= mina3 a)) (set! mina3 "BOOM") (set! mina3 ""))
  (if (not(= mina4 a)) (set! mina4 "BOOM") (set! mina4 ""))  
  (if (not(= mina5 a)) (set! mina5 "BOOM") (set! mina5 ""))
  (if (not(= mina6 a)) (set! mina6 "BOOM") (set! mina6 ""))
  (if (not(= mina7 a)) (set! mina7 "BOOM") (set! mina7 ""))  
  (if (not(= mina8 a)) (set! mina8 "BOOM") (set! mina8 ""))
  (if (not(= mina9 a)) (set! mina9 "BOOM") (set! mina9 ""))
  (if (not(= mina10 a)) (set! mina10 "BOOM") (set! mina10 ""))
  (if (not(= mina11 a)) (set! mina11 "BOOM") (set! mina11 ""))
  (if (not(= mina12 a)) (set! mina12 "BOOM") (set! mina12 ""))
  (if (not(= mina13 a)) (set! mina13 "BOOM") (set! mina13 ""))
  (if (not(= mina14 a)) (set! mina14 "BOOM") (set! mina14 ""))
  (if (not(= mina15 a)) (set! mina15 "BOOM") (set! mina15 ""))
  (if (not(= mina16 a)) (set! mina16 "BOOM") (set! mina16 ""))
  (if (not(= mina17 a)) (set! mina17 "BOOM") (set! mina17 ""))
  (if (not(= mina18 a)) (set! mina18 "BOOM") (set! mina18 ""))
  (if (not(= mina19 a)) (set! mina19 "BOOM") (set! mina19 ""))
  (if (not(= mina20 a)) (set! mina20 "BOOM") (set! mina20 ""))
  (if (not(= mina21 a)) (set! mina21 "BOOM") (set! mina21 ""))
  (if (not(= mina22 a)) (set! mina22 "BOOM") (set! mina22 ""))
  (if (not(= mina23 a)) (set! mina23 "BOOM") (set! mina23 ""))
  (if (not(= mina24 a)) (set! mina24 "BOOM") (set! mina24 ""))
  (if (not(= mina25 a)) (set! mina25 "BOOM") (set! mina25 ""))
  (if (not(= mina26 a)) (set! mina26 "BOOM") (set! mina26 ""))
  (if (not(= mina27 a)) (set! mina27 "BOOM") (set! mina27 ""))
  (if (not(= mina28 a)) (set! mina28 "BOOM") (set! mina28 ""))
  (if (not(= mina29 a)) (set! mina29 "BOOM") (set! mina29 ""))
  (if (not(= mina30 a)) (set! mina30 "BOOM") (set! mina30 ""))
  (if (not(= mina31 a)) (set! mina31 "BOOM") (set! mina31 ""))
  (if (not(= mina32 a)) (set! mina32 "BOOM") (set! mina32 ""))
  (if (not(= mina33 a)) (set! mina33 "BOOM") (set! mina33 ""))
  (if (not(= mina34 a)) (set! mina34 "BOOM") (set! mina34 ""))
  (if (not(= mina35 a)) (set! mina35 "BOOM") (set! mina35 ""))
  (if (not(= mina36 a)) (set! mina36 "BOOM") (set! mina36 ""))
  
  (if  (string=? mina1 mina2 mina3 mina4 mina5 mina6 mina7 mina8 mina9 mina10 mina11 mina12 mina13 mina14 mina15 mina16 "BOOM")
    (begin (procesoasignarmina b)(procesovariablemina2 a b)) (display ""))
  
  (if  (string=? mina1 mina2 mina3 mina4 mina5 mina6 mina7 mina8 mina9 mina10 mina11 mina12 mina13 mina14 mina15 mina16
                  mina17 mina18 mina19 mina20 mina21 mina22 mina23 mina24 mina25 "BOOM")
    (begin (procesoasignarmina b)(procesovariablemina2 a b)) (display ""))
  
  (if  (string=? mina1 mina2 mina3 mina4 mina5 mina6 mina7 mina8 mina9 mina10 mina11 mina12 mina13 mina14 mina15 mina16
                  mina17 mina18 mina19 mina20 mina21 mina22 mina23 mina24 mina25 mina26 mina27 mina28 mina29 mina30 mina31
                   mina32 mina33 mina34 mina35 mina36 "BOOM")
    (begin (procesoasignarmina b)(procesovariablemina2 a b)) (display ""))

  )
;__________________________________________________________________FUNCION PARA ASIGNAR LOS ICONOS CON BOMBA_________________________________________________________________________________________________________________________________________________
(define (asignaricono)
  (if (string=? mina1 "BOOM") (set! minaI1 (bomb-icon #:height 25)) (set! minaI1 ""))
  (if (string=? mina2 "BOOM") (set! minaI2 (bomb-icon #:height 25)) (set! minaI2 ""))
  (if (string=? mina3 "BOOM") (set! minaI3 (bomb-icon #:height 25)) (set! minaI3 ""))
  (if (string=? mina4 "BOOM") (set! minaI4 (bomb-icon #:height 25)) (set! minaI4 ""))  
  (if (string=? mina5 "BOOM") (set! minaI5 (bomb-icon #:height 25)) (set! minaI5 ""))
  (if (string=? mina6 "BOOM") (set! minaI6 (bomb-icon #:height 25)) (set! minaI6 ""))
  (if (string=? mina7 "BOOM") (set! minaI7 (bomb-icon #:height 25)) (set! minaI7 ""))  
  (if (string=? mina8 "BOOM") (set! minaI8 (bomb-icon #:height 25)) (set! minaI8 ""))
  (if (string=? mina9 "BOOM") (set! minaI9 (bomb-icon #:height 25)) (set! minaI9 ""))
  (if (string=? mina10 "BOOM") (set! minaI10 (bomb-icon #:height 25)) (set! minaI10 ""))
  (if (string=? mina11 "BOOM") (set! minaI11 (bomb-icon #:height 25)) (set! minaI11 ""))
  (if (string=? mina12 "BOOM") (set! minaI12 (bomb-icon #:height 25)) (set! minaI12 ""))
  (if (string=? mina13 "BOOM") (set! minaI13 (bomb-icon #:height 25)) (set! minaI13 ""))
  (if (string=? mina14 "BOOM") (set! minaI14 (bomb-icon #:height 25)) (set! minaI14 ""))
  (if (string=? mina15 "BOOM") (set! minaI15 (bomb-icon #:height 25)) (set! minaI15 ""))
  (if (string=? mina16 "BOOM") (set! minaI16 (bomb-icon #:height 25)) (set! minaI16 ""))
  (if (string=? mina17 "BOOM") (set! minaI17 (bomb-icon #:height 25)) (set! minaI17 ""))
  (if (string=? mina18 "BOOM") (set! minaI18 (bomb-icon #:height 25)) (set! minaI18 ""))
  (if (string=? mina19 "BOOM") (set! minaI19 (bomb-icon #:height 25)) (set! minaI19 ""))
  (if (string=? mina20 "BOOM") (set! minaI20 (bomb-icon #:height 25)) (set! minaI20 ""))
  (if (string=? mina21 "BOOM") (set! minaI21 (bomb-icon #:height 25)) (set! minaI21 ""))
  (if (string=? mina22 "BOOM") (set! minaI22 (bomb-icon #:height 25)) (set! minaI22 ""))
  (if (string=? mina23 "BOOM") (set! minaI23 (bomb-icon #:height 25)) (set! minaI23 ""))
  (if (string=? mina24 "BOOM") (set! minaI24 (bomb-icon #:height 25)) (set! minaI24 ""))
  (if (string=? mina25 "BOOM") (set! minaI25 (bomb-icon #:height 25)) (set! minaI25 ""))
  (if (string=? mina26 "BOOM") (set! minaI26 (bomb-icon #:height 25)) (set! minaI26 ""))
  (if (string=? mina27 "BOOM") (set! minaI27 (bomb-icon #:height 25)) (set! minaI27 ""))
  (if (string=? mina28 "BOOM") (set! minaI28 (bomb-icon #:height 25)) (set! minaI28 ""))
  (if (string=? mina29 "BOOM") (set! minaI29 (bomb-icon #:height 25)) (set! minaI29 ""))
  (if (string=? mina30 "BOOM") (set! minaI30 (bomb-icon #:height 25)) (set! minaI30 ""))
  (if (string=? mina31 "BOOM") (set! minaI31 (bomb-icon #:height 25)) (set! minaI31 ""))
  (if (string=? mina32 "BOOM") (set! minaI32 (bomb-icon #:height 25)) (set! minaI32 ""))
  (if (string=? mina33 "BOOM") (set! minaI33 (bomb-icon #:height 25)) (set! minaI33 ""))
  (if (string=? mina34 "BOOM") (set! minaI34 (bomb-icon #:height 25)) (set! minaI34 ""))
  (if (string=? mina35 "BOOM") (set! minaI35 (bomb-icon #:height 25)) (set! minaI35 ""))
  (if (string=? mina36 "BOOM") (set! minaI36 (bomb-icon #:height 25)) (set! minaI36 "")))

;___________________________________________________________FUNCION PARA CAPTURAR EL NOMBRE___________________________________________________________________________________________________________________________________________________________
(define nombre1 "-")
(define (capturarnombre a)
  (if (equal? (send a get-value) "") (set! nombre1 "Anonimo") (set! nombre1 (send a get-value))))
;________________________________________________________SETEO DE VARIABLE PARA TERMINAR JUEGO______________________________________________________________________________________________________________________________________________________
(define terminar true)
(define puntuacion "dd")
(define botonessinboom 0) 
(define botonespre 0)

(define (procesoterminar a)
  (if (or (= botonessinboom botonespre)(string=? a  "BOOM")) (begin(Ptiempofinal)
                                                                   (set! puntuacion (number->string (* (/  botonespre botonessinboom) 100)))
                                                                   (agregaralista)
                                                                   (set! terminar false)
                                                                   (procesoescribir Recordjugadores)
                                                                   ) (display "")))
;________________________________________________________INHABILITAR BOTONES Y TERMINAR JUEGO_____________________________________________________________________________________________________________________________________________________
;_____________________Para tablero 4x4_________________________________________________________________________________________________________________________________________________________________________
(define (procesoterminar2 a b c d e f g h i j k l m n o p q pp)
  (if (equal? terminar false)
   (begin (send a enable terminar)
   (send b enable terminar)
   (send c enable terminar)
   (send d enable terminar)
   (send e enable terminar)
   (send f enable terminar)
   (send g enable terminar)
   (send h enable terminar)
   (send i enable terminar)
   (send j enable terminar)
   (send k enable terminar)
   (send l enable terminar)
   (send m enable terminar)
   (send n enable terminar)
   (send o enable terminar)
   (send p enable terminar)
   (send pp set-label (string-append "Su puntuacion es: " puntuacion))
   (send q show #t)) (display "")))

;____________________Para tablero 5x5____________________________________________________________________________________________________________________________________________________________________________
(define (procesoterminar22 a b c d e f g h i j k l m n o p q r s t u v w x y qq pp)
  (if (equal? terminar false)
   (begin (send a enable terminar)
   (send b enable terminar)
   (send c enable terminar)
   (send d enable terminar)
   (send e enable terminar)
   (send f enable terminar)
   (send g enable terminar)
   (send h enable terminar)
   (send i enable terminar)
   (send j enable terminar)
   (send k enable terminar)
   (send l enable terminar)
   (send m enable terminar)
   (send n enable terminar)
   (send o enable terminar)
   (send p enable terminar)
   (send q enable terminar)
   (send r enable terminar)
   (send s enable terminar)
   (send t enable terminar)
   (send u enable terminar)
   (send v enable terminar)
   (send w enable terminar)
   (send x enable terminar)
   (send y enable terminar)
   (send pp set-label (string-append "Su puntuacion es: " puntuacion));Label de ventana que se muestra al terminar cada juego
   (send qq show #t));Mostrar ventana al terminar el juego
   (display "")))
;______________________Para tablero 6x6_________________________________________________________________________________________________________________________________________________________________________
(define (procesoterminar3 a b c d e f g h i j k l m n o p q r s t u v w x y z aa bb cc dd ee ff gg hh ii jj qq pp)
  (if (equal? terminar false)
   (begin (send a enable terminar)
   (send b enable terminar)
   (send c enable terminar)
   (send d enable terminar)
   (send e enable terminar)
   (send f enable terminar)
   (send g enable terminar)
   (send h enable terminar)
   (send i enable terminar)
   (send j enable terminar)
   (send k enable terminar)
   (send l enable terminar)
   (send m enable terminar)
   (send n enable terminar)
   (send o enable terminar)
   (send p enable terminar)
   (send q enable terminar)
   (send r enable terminar)
   (send s enable terminar)
   (send t enable terminar)
   (send u enable terminar)
   (send v enable terminar)
   (send w enable terminar)
   (send x enable terminar)
   (send y enable terminar)
   (send z enable terminar)
   (send aa enable terminar)
   (send bb enable terminar)
   (send cc enable terminar)
   (send dd enable terminar)
   (send ee enable terminar)
   (send ff enable terminar)
   (send gg enable terminar)
   (send hh enable terminar)
   (send ii enable terminar)
   (send jj enable terminar)
   (send pp set-label (string-append "Su puntuacion es: " puntuacion));Label de ventana que se muestra al terminar cada juego
   (send qq show #t));Mostrar ventana al terminar el juego
   (display "")))




;____________________________________________________CONTAR BOTONES SIN BOMBA____________________________________________________________________________________________________________________________________________________________________
;______________________________Para tablero 4x4                       
(define (procesocontar)
  (if (equal? mina1 "") (set! botonessinboom (+ botonessinboom 1)) (display ""))
  (if (equal? mina2 "") (set! botonessinboom (+ botonessinboom 1)) (display ""))
  (if (equal? mina3 "") (set! botonessinboom (+ botonessinboom 1)) (display ""))
  (if (equal? mina4 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina5 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina6 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina7 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina8 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina9 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina10 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina11 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina12 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina13 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina14 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina15 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina16 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) )
;______________________________Para tablero 5x5
(define (procesocontar2)
  (if (equal? mina1 "") (set! botonessinboom (+ botonessinboom 1)) (display ""))
  (if (equal? mina2 "") (set! botonessinboom (+ botonessinboom 1)) (display ""))
  (if (equal? mina3 "") (set! botonessinboom (+ botonessinboom 1)) (display ""))
  (if (equal? mina4 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina5 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina6 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina7 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina8 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina9 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina10 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina11 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina12 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina13 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina14 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina15 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina16 "") (set! botonessinboom (+ botonessinboom 1)) (display ""))
  (if (equal? mina17 "") (set! botonessinboom (+ botonessinboom 1)) (display ""))
  (if (equal? mina18 "") (set! botonessinboom (+ botonessinboom 1)) (display ""))
  (if (equal? mina19 "") (set! botonessinboom (+ botonessinboom 1)) (display ""))
  (if (equal? mina20 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina21 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina22 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina23 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina24 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina25 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) )
;______________________________Para tablero 6x6
(define (procesocontar3)
  (if (equal? mina1 "") (set! botonessinboom (+ botonessinboom 1)) (display ""))
  (if (equal? mina2 "") (set! botonessinboom (+ botonessinboom 1)) (display ""))
  (if (equal? mina3 "") (set! botonessinboom (+ botonessinboom 1)) (display ""))
  (if (equal? mina4 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina5 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina6 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina7 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina8 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina9 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina10 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina11 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina12 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina13 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina14 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina15 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina16 "") (set! botonessinboom (+ botonessinboom 1)) (display ""))
  (if (equal? mina17 "") (set! botonessinboom (+ botonessinboom 1)) (display ""))
  (if (equal? mina18 "") (set! botonessinboom (+ botonessinboom 1)) (display ""))
  (if (equal? mina19 "") (set! botonessinboom (+ botonessinboom 1)) (display ""))
  (if (equal? mina20 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina21 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina22 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina23 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina24 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina25 "") (set! botonessinboom (+ botonessinboom 1)) (display ""))
  (if (equal? mina26 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina27 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina28 "") (set! botonessinboom (+ botonessinboom 1)) (display ""))
  (if (equal? mina29 "") (set! botonessinboom (+ botonessinboom 1)) (display ""))
  (if (equal? mina30 "") (set! botonessinboom (+ botonessinboom 1)) (display ""))
  (if (equal? mina31 "") (set! botonessinboom (+ botonessinboom 1)) (display ""))
  (if (equal? mina32 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina33 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina34 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina35 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  (if (equal? mina36 "") (set! botonessinboom (+ botonessinboom 1)) (display "")) 
  )
;____________________________________________________________FUNCION PARA CONTAR LAS JUGADAS______________________________________________________________________________________________________________________________________________________________  
(define (procescontarpresionandoboton a)
  (if (equal? a "") (set! botonespre (+ botonespre 1)) (display "")))

;_____________________________________________________FUNCIONES PARA DETERMINAR EL TIEMPO DE JUEGO_____________________________________________________________________________________________________________________________________________
(define tiempoinicial 0)
(define tiempofinal 0)

(define (Ptiempoinicial)
(set! tiempoinicial (current-seconds)))
  
(define (Ptiempofinal)
(set! tiempofinal (string-append(number->string(-(current-seconds) tiempoinicial)) "seg")))

;____________________________________________________________FUNCION PARA LA FECHA Y HORA______________________________________________________________________________________________________________________________________________________________
(define date "")
(define año "")
(define mes "")
(define dia "")
(define fecha "")
(define hora "")
(define minutos "")
(define horaI "") ;Hora inicial 
(define (funcionfechayhora)
  (set! date (current-date))
  (set! hora (if (< (date-hour date) 10) (string-append "0" (number->string (date-hour date))) (number->string (date-hour date))))
  (set! minutos (if (< (date-minute date) 10) (string-append "0" (number->string(date-minute date))) (number->string (date-minute date))))
  (set! horaI (string-append hora ":" minutos)) 
  (set! año (number->string (date-year (current-date))))
  (set! mes (if (< (date-month date) 10) (string-append "0" (number->string(date-month date))) (number->string (date-month date))))
  (set! dia (if (< (date-day date) 10) (string-append "0" (number->string(date-day date))) (number->string (date-day date))))
  (set! fecha (string-append dia "/" mes "/" año)))



;____________________________________________________________FUNCION AGREGAR EN LISTA____________________________________________________________________________________________________________________________________________________________________
(define (agregaralista)
  (set! Recordjugadores (append Recordjugadores (list (make-Jugadores nombre1 fecha horaI tiempofinal puntuacion (number->string botonespre))))))





;___________________________________________________FUNCION PARA LEER JUGADORES DEL TEXTO PLANO______________________________________________________________________________________________________________________________________________
(define lectura "")
(define nombre "")
(define fecha1 "")
(define horaI1 "")
(define tiempofinal1 "")
(define puntuacion1 "")
(define botonespre1 "")

(define(procesoleer)
  (define guardado "")
  (define lec "")

  (if (file-exists? "Guardar.txt")
           (begin(set! guardado "Guardar.txt")
               (set! lec (open-input-file guardado)) 
               (do ()
                   ((eof-object? lectura))
                    (procesoleer1)
                    (set! lectura (read-line lec))
          
                ) (close-input-port lec))
              (display "")))

(define (procesoleer1)
(define contadorleer 0)
(define contadorvariable 0)

  (if (file-exists? "Guardar.txt")
      (begin (do ()
             ((>= contadorleer (string-length lectura)))
                                
               (if (equal? (string-ref lectura contadorleer) #\%) (begin(set! contadorvariable (+ contadorvariable 1)) (set! contadorleer(+ contadorleer 1))) (display ""))
                 (if (= contadorvariable 7)
                      (begin (set! Recordjugadores (append Recordjugadores (list (make-Jugadores nombre fecha1 horaI1 tiempofinal1 puntuacion1  botonespre1))))
                             (set! contadorvariable 0) 
                             (set! nombre "")
                             (set! fecha1 "")
                             (set! horaI1 "")
                             (set! tiempofinal1 "")
                             (set! puntuacion1 "")
                             (set! botonespre1 "")) (display ""))
               (cond
                 [(= contadorvariable 1)(set! nombre (string-append nombre (string(string-ref lectura contadorleer))))]
                 [(= contadorvariable 2)(set! fecha1 (string-append fecha1 (string(string-ref lectura contadorleer))))]
                 [(= contadorvariable 3)(set! horaI1 (string-append horaI1 (string(string-ref lectura contadorleer))))]
                 [(= contadorvariable 4)(set! tiempofinal1 (string-append tiempofinal1 (string(string-ref lectura contadorleer))))]
                 [(= contadorvariable 5)(set! puntuacion1 (string-append puntuacion1 (string(string-ref lectura contadorleer))))]
                 [(= contadorvariable 6)(set! botonespre1 (string-append botonespre1 (string(string-ref lectura contadorleer))))]
                 )
            

   

               (set! contadorleer (+ contadorleer 1)))) (display "")))

;_____________________________________________________FUNCION PARA ESCRIBIR LOS JUGADORES EN TEXTO PLANO_______________________________________________________________________________________________________________________________________
(define (procesoescribir Recordjugadores)
(define contadorg 0)
  
 (if (file-exists? "Guardar.txt")(delete-file "Guardar.txt") (display ""))
            (define guar (open-output-file "Guardar.txt"))
               (do ()
                 ((or (= contadorg (length Recordjugadores))))
                 (display (string-append "%"(Jugadores-nombre (list-ref Recordjugadores contadorg))"%"(Jugadores-fecha (list-ref Recordjugadores contadorg))"%"(Jugadores-hora (list-ref Recordjugadores contadorg))"%"
                          (Jugadores-tiempodejuego (list-ref Recordjugadores contadorg))"%"(Jugadores-puntaje (list-ref Recordjugadores contadorg))"%"
                          (Jugadores-totaljugadas (list-ref Recordjugadores contadorg))"%") guar)
                 (newline guar)
                 (set! contadorg (+ contadorg 1)) 
                 )
  (close-output-port guar)
  )
;_______________________________________________________FUCNION PARA DETERMINAR EL PUNTAJE MAS ALTO______________________________________________________________________________________________________________________________________________________
(define TotalE "")
(define vectorEs "")
(define vector1 "")
(define puntajeA "")
(define (puntajealto)
   (if  (file-exists? "Guardar.txt")
      (begin (set! TotalE (length Recordjugadores))
             (set! vectorEs(make-vector TotalE))
             (set! vector1 0)
             (do ()
               ((= vector1 TotalE))
               (vector-set! vectorEs  vector1 (string->number(Jugadores-puntaje (list-ref Recordjugadores vector1 ))))
               (set! vector1(+ vector1 1)))
             (set! puntajeA (vector-argmax values vectorEs))
             (set! vector1 0 )
              (procesomostrar)) (display "")))

(define contador 0)
(define nombreAl "")
;__________________________________________________FUNCION PARA MOSTRAR EL NOMBRE Y EL PUNTAJE MAS ALTO_______________________________________________________________________________________________________________________________________
(define (procesomostrar)
  (do ()
    ((= contador (length Recordjugadores)))
    (if (= (string->number(Jugadores-puntaje(list-ref Recordjugadores contador))) puntajeA) (procesonombrejugador Recordjugadores contador) (display""))
    (set! contador (+ contador 1)))
  (set! contador 0))
(define (procesonombrejugador x d)
   (set! nombreAl (string-append nombreAl "-" (Jugadores-nombre (list-ref x d)) " " (Jugadores-puntaje (list-ref x d))))
  )

;___________________________________________________________________________NUEVO JUEGO___________________________________________________________________________________________________________________________________________________

(define (reset)
  (set! terminar true)
  (set! botonessinboom 0) 
  (set! botonespre 0)
  (set! puntuacion "0")
  )

;________________________________________ LIMPIAR BOTONES 4X4_______________________________________

(define (reset4 A1 A2 A3 A4 B1 B2 B3 B4 C1 C2 C3 C4 D1 D2 D3 D4)

  (send A1 enable true)
  (send A2 enable true)
  (send A3 enable true)
  (send A4 enable true)
  (send B1 enable true)
  (send B2 enable true)
  (send B3 enable true)
  (send B4 enable true)
  (send C1 enable true)
  (send C2 enable true)
  (send C3 enable true)
  (send C4 enable true)
  (send D1 enable true)
  (send D2 enable true)
  (send D3 enable true)
  (send D4 enable true)
  
  (send A1 set-label (stop-icon #:color "white" #:height 25))
  (send A2 set-label (stop-icon #:color "white" #:height 25))
  (send A3 set-label (stop-icon #:color "white" #:height 25))
  (send A4 set-label (stop-icon #:color "white" #:height 25))
  (send B1 set-label (stop-icon #:color "white" #:height 25))
  (send B2 set-label (stop-icon #:color "white" #:height 25))
  (send B3 set-label (stop-icon #:color "white" #:height 25))
  (send B4 set-label (stop-icon #:color "white" #:height 25))
  (send C1 set-label (stop-icon #:color "white" #:height 25))
  (send C2 set-label (stop-icon #:color "white" #:height 25))
  (send C3 set-label (stop-icon #:color "white" #:height 25))
  (send C4 set-label (stop-icon #:color "white" #:height 25))
  (send D1 set-label (stop-icon #:color "white" #:height 25))
  (send D2 set-label (stop-icon #:color "white" #:height 25))
  (send D3 set-label (stop-icon #:color "white" #:height 25))
  (send D4 set-label (stop-icon #:color "white" #:height 25))
  
  (reset)
  )

;________________________________________ LIMPIAR BOTONES 5X5_______________________________________

(define (reset5 AA51 AA52 AA53 AA54 AA55 BB51 BB52 BB53 BB54 BB55
                CC51 CC52 CC53 CC54 CC55 DD51 DD52 DD53 DD54 DD55
                EE51 EE52 EE53 EE54 EE55)

  (send AA51 enable true)
  (send AA52 enable true)
  (send AA53 enable true)
  (send AA54 enable true)
  (send AA55 enable true)
  (send BB51 enable true)
  (send BB52 enable true)
  (send BB53 enable true)
  (send BB54 enable true)
  (send BB55 enable true)
  (send CC51 enable true)
  (send CC52 enable true)
  (send CC53 enable true)
  (send CC54 enable true)
  (send CC55 enable true)
  (send DD51 enable true)
  (send DD52 enable true)
  (send DD53 enable true)
  (send DD54 enable true)
  (send DD55 enable true)
  (send EE51 enable true)
  (send EE52 enable true)
  (send EE53 enable true)
  (send EE54 enable true)
  (send EE55 enable true)

  (send AA51 set-label (stop-icon #:color "white" #:height 25))
  (send AA52 set-label (stop-icon #:color "white" #:height 25))
  (send AA53 set-label (stop-icon #:color "white" #:height 25))
  (send AA54 set-label (stop-icon #:color "white" #:height 25))
  (send AA55 set-label (stop-icon #:color "white" #:height 25))
  (send BB51 set-label (stop-icon #:color "white" #:height 25))
  (send BB52 set-label (stop-icon #:color "white" #:height 25))
  (send BB53 set-label (stop-icon #:color "white" #:height 25))
  (send BB54 set-label (stop-icon #:color "white" #:height 25))
  (send BB55 set-label (stop-icon #:color "white" #:height 25))
  (send CC51 set-label (stop-icon #:color "white" #:height 25))
  (send CC52 set-label (stop-icon #:color "white" #:height 25))
  (send CC53 set-label (stop-icon #:color "white" #:height 25))
  (send CC54 set-label (stop-icon #:color "white" #:height 25))
  (send CC55 set-label (stop-icon #:color "white" #:height 25))
  (send DD51 set-label (stop-icon #:color "white" #:height 25))
  (send DD52 set-label (stop-icon #:color "white" #:height 25))
  (send DD53 set-label (stop-icon #:color "white" #:height 25))
  (send DD54 set-label (stop-icon #:color "white" #:height 25))
  (send DD55 set-label (stop-icon #:color "white" #:height 25))
  (send EE51 set-label (stop-icon #:color "white" #:height 25))
  (send EE52 set-label (stop-icon #:color "white" #:height 25))
  (send EE53 set-label (stop-icon #:color "white" #:height 25))
  (send EE54 set-label (stop-icon #:color "white" #:height 25))
  (send EE55 set-label (stop-icon #:color "white" #:height 25))
  
  (reset)
  )

;________________________________________ LIMPIAR BOTONES 6X6_______________________________________

(define (reset6 AA1 AA2 AA3 AA4 AA5 AA6 BB1 BB2 BB3 BB4 BB5 BB6
                CC1 CC2 CC3 CC4 CC5 CC6 DD1 DD2 DD3 DD4 DD5 DD6
                EE1 EE2 EE3 EE4 EE5 EE6 FF1 FF2 FF3 FF4 FF5 FF6)
  (send AA1 enable true)
  (send AA2 enable true)
  (send AA3 enable true)
  (send AA4 enable true)
  (send AA5 enable true)
  (send AA6 enable true)
  (send BB1 enable true)
  (send BB2 enable true)
  (send BB3 enable true)
  (send BB4 enable true)
  (send BB5 enable true)
  (send BB6 enable true)
  (send CC1 enable true)
  (send CC2 enable true)
  (send CC3 enable true)
  (send CC4 enable true)
  (send CC5 enable true)
  (send CC6 enable true)
  (send DD1 enable true)
  (send DD2 enable true)
  (send DD3 enable true)
  (send DD4 enable true)
  (send DD5 enable true)
  (send DD6 enable true)
  (send EE1 enable true)
  (send EE2 enable true)
  (send EE3 enable true)
  (send EE4 enable true)
  (send EE5 enable true)
  (send EE6 enable true)
  (send FF1 enable true)
  (send FF2 enable true)
  (send FF3 enable true)
  (send FF4 enable true)
  (send FF5 enable true)
  (send FF6 enable true)

  (send AA1 set-label (stop-icon #:color "white" #:height 25))
  (send AA2 set-label (stop-icon #:color "white" #:height 25))
  (send AA3 set-label (stop-icon #:color "white" #:height 25))
  (send AA4 set-label (stop-icon #:color "white" #:height 25))
  (send AA5 set-label (stop-icon #:color "white" #:height 25))
  (send AA6 set-label (stop-icon #:color "white" #:height 25))
  (send BB1 set-label (stop-icon #:color "white" #:height 25))
  (send BB2 set-label (stop-icon #:color "white" #:height 25))
  (send BB3 set-label (stop-icon #:color "white" #:height 25))
  (send BB4 set-label (stop-icon #:color "white" #:height 25))
  (send BB5 set-label (stop-icon #:color "white" #:height 25))
  (send BB6 set-label (stop-icon #:color "white" #:height 25))
  (send CC1 set-label (stop-icon #:color "white" #:height 25))
  (send CC2 set-label (stop-icon #:color "white" #:height 25))
  (send CC3 set-label (stop-icon #:color "white" #:height 25))
  (send CC4 set-label (stop-icon #:color "white" #:height 25))
  (send CC5 set-label (stop-icon #:color "white" #:height 25))
  (send CC6 set-label (stop-icon #:color "white" #:height 25))
  (send DD1 set-label (stop-icon #:color "white" #:height 25))
  (send DD2 set-label (stop-icon #:color "white" #:height 25))
  (send DD3 set-label (stop-icon #:color "white" #:height 25))
  (send DD4 set-label (stop-icon #:color "white" #:height 25))
  (send DD5 set-label (stop-icon #:color "white" #:height 25))
  (send DD6 set-label (stop-icon #:color "white" #:height 25))
  (send EE1 set-label (stop-icon #:color "white" #:height 25))
  (send EE2 set-label (stop-icon #:color "white" #:height 25))
  (send EE3 set-label (stop-icon #:color "white" #:height 25))
  (send EE4 set-label (stop-icon #:color "white" #:height 25))
  (send EE5 set-label (stop-icon #:color "white" #:height 25))
  (send EE6 set-label (stop-icon #:color "white" #:height 25))
  (send FF1 set-label (stop-icon #:color "white" #:height 25))
  (send FF2 set-label (stop-icon #:color "white" #:height 25))
  (send FF3 set-label (stop-icon #:color "white" #:height 25))
  (send FF4 set-label (stop-icon #:color "white" #:height 25))
  (send FF5 set-label (stop-icon #:color "white" #:height 25))
  (send FF6 set-label (stop-icon #:color "white" #:height 25))
  
  (reset)
  )

;________________________VALIDACIÓN NOMBRE_________________________________________________________________________________________________________________________________________
(define nombreN "")

(define (validanombre nombre noti notificacion juego)
  (if (equal? nombre "")
      (send noti show #t)
      (begin
        (set! nombreN (string->number nombre))
        (if (equal? nombreN #f)
            (send juego show #t)
            (begin (send notificacion set-label "El nombre no debe contener numeros") (send noti show #t)))))
  )

;__________________________REINICIAR PUNTAJES_________________________________________________________________________________________________________________________________________-
(define (reiniciarpuntaje puntaje)
(if (file-exists? "Guardar.txt")
                               (begin (delete-file "Guardar.txt")
                                      (set! nombreAl "")
                                      (send puntaje set-value nombreAl))
                                      (display "")))

